### ISSUE TITLE
Brachy slime shiny causes large monster hp to get unlisted

### ISSUE THREAD

**Issue by Aeternalia** [Alexander-Lancellott/MH3U-MH3G-HP-Overlay-For-WiiU-Emulator#2]
It seems that whenever Brachy's slime pops and drops a shiny, one of the large monster's hp will get unlisted from the overlay. It's somewhat easy to test this with the double brachy quest in G rank but it can take a bit for a shiny to drop from a slime puddle.

**Comment by Aeternalia** [comment]
I have a feeling that this may happen when shinies drop in general as the hp got unlisted even in a solo monster quest after a shiny drop.

**Comment by Alexander-Lancellott** [comment]
I was reviewing this, and it turned out to be an issue with the pattern I was previously using for the AOB scan. It seems that the memory section I was scanning has some bytes reserved for shiny drops, which caused the pattern to stop matching, and as a result, the monster's information was no longer found. I've replaced it with another pattern that seems much more stable for now—at least in the tests I ran, I didn't encounter any issues. However, I still can't confirm that it's perfect, so if you notice any bugs with [version 1.0.1](https://github.com/Alexander-Lancellott/MH3U-MH3G-HP-Overlay-For-WiiU-Emulator/releases/tag/v1.0.1), which I released a few minutes ago, please report them again.
